
namespace ImprovementArsenalPlugin
{
    public partial class IATable
    {
        public static IATable[] List = new IATable[] {
            new IATable { Equip = "12.7cm連装砲", Info = "1/1+12.7cm連装砲(1)/3+12.7cm連装砲(2)　⇒12.7cm連装砲B型改二", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = ""},
            new IATable { Equip = "12.7cm連装砲B型改二", Info = "2/2+12.7cm連装砲(1)/4+12.7cm連装砲(3)　⇒12.7cm連装砲C型改二", Days = new string[] {"月","火","水"}, ShipName = "綾波改二"},
            new IATable { Equip = "12.7cm連装砲B型改二", Info = "2/2+12.7cm連装砲(1)/4+12.7cm連装砲(3)　⇒12.7cm連装砲C型改二", Days = new string[] {"月","火","水"}, ShipName = "夕立改二"},
            new IATable { Equip = "12.7cm連装砲B型改二", Info = "2/2+12.7cm連装砲(1)/4+12.7cm連装砲(3)　⇒12.7cm連装砲C型改二", Days = new string[] {"月","火","水","木"}, ShipName = "江風改二"},
            new IATable { Equip = "12.7cm連装砲C型改二", Info = "2+12.7cm連装砲(1)/3+12.7cm連装砲(1)/4+22号対水上電探(2)+新型砲熕兵装資材(1)+戦闘詳報(1)　⇒12.7cm連装砲D型改二", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "満潮改二"},
            new IATable { Equip = "12.7cm連装砲C型改二", Info = "2+12.7cm連装砲(1)/3+12.7cm連装砲(1)/4+22号対水上電探(2)+新型砲熕兵装資材(1)+戦闘詳報(1)　⇒12.7cm連装砲D型改二", Days = new string[] {"水","木","金","土"}, ShipName = "荒潮改二"},
            new IATable { Equip = "12.7cm連装砲C型改二", Info = "2+12.7cm連装砲(1)/3+12.7cm連装砲(1)/4+22号対水上電探(2)+新型砲熕兵装資材(1)+戦闘詳報(1)　⇒12.7cm連装砲D型改二", Days = new string[] {"木","金","土"}, ShipName = "雪風改"},
            new IATable { Equip = "12.7cm連装砲D型改二", Info = "5+10cm連装高角砲(2)/6+10cm連装高角砲(1)", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "長波改二"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "3/4+10cm連装高角砲(2)", Days = new string[] {"月","火","水","木"}, ShipName = "秋月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "3/4+10cm連装高角砲(2)", Days = new string[] {"月","火","水","木"}, ShipName = "初月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "3/4+10cm連装高角砲(2)", Days = new string[] {"日","木","金","土"}, ShipName = "照月"},
            new IATable { Equip = "14cm単装砲", Info = "1/1+14cm単装砲(1)/3+14cm単装砲(2)　⇒14cm連装砲", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = ""},
            new IATable { Equip = "14cm連装砲", Info = "1/2+14cm連装砲", Days = new string[] {"月","木"}, ShipName = "夕張"},
            new IATable { Equip = "15.2cm連装砲", Info = "2/2+15.2cm連装砲(1)/4+15.2cm連装砲(1)　⇒15.2cm連装砲改", Days = new string[] {"木","金","土"}, ShipName = "阿賀野"},
            new IATable { Equip = "15.2cm連装砲", Info = "2/2+15.2cm連装砲(1)/4+15.2cm連装砲(1)　⇒15.2cm連装砲改", Days = new string[] {"日","月","金","土"}, ShipName = "能代"},
            new IATable { Equip = "15.2cm連装砲", Info = "2/2+15.2cm連装砲(1)/4+15.2cm連装砲(1)　⇒15.2cm連装砲改", Days = new string[] {"月","火","水","木"}, ShipName = "矢矧"},
            new IATable { Equip = "15.2cm連装砲改", Info = "2+15.2cm連装砲(1)/3+15.2cm連装砲(1)", Days = new string[] {"水","木","金","土"}, ShipName = "矢矧"},
            new IATable { Equip = "15.2cm連装砲改", Info = "2+15.2cm連装砲(1)/3+15.2cm連装砲(1)", Days = new string[] {"日","月","火","土"}, ShipName = "酒匂"},
            new IATable { Equip = "15.5cm三連装砲", Info = "2/2+15.5cm三連装砲(1)/4+15.5cm三連装砲(2)+新型砲熕兵装資材(1)　⇒15.5cm三連装砲改(大淀)", Days = new string[] {"金","土"}, ShipName = "最上"},
            new IATable { Equip = "15.5cm三連装砲", Info = "2/2+15.5cm三連装砲(1)/4+15.5cm三連装砲(2)+新型砲熕兵装資材(1)　⇒15.5cm三連装砲改(大淀)", Days = new string[] {"日","月","金","土"}, ShipName = "大淀"},
            new IATable { Equip = "15.5cm三連装砲改", Info = "4+15.5cm三連装砲(2)/5+15.5cm三連装副砲(2)/2+15.5cm三連装副砲(1)　⇒15.5cm三連装副砲改★+7", Days = new string[] {"日","金","土"}, ShipName = "大淀改"},
            new IATable { Equip = "20.3cm連装砲", Info = "2/2+20.3cm連装砲(1)/4+20.3cm連装砲(2)　⇒20.3cm(2号)連装砲", Days = new string[] {"日","木","金","土"}, ShipName = "青葉"},
            new IATable { Equip = "20.3cm連装砲", Info = "2/2+20.3cm連装砲(1)/4+20.3cm連装砲(2)　⇒20.3cm(2号)連装砲", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "衣笠"},
            new IATable { Equip = "20.3cm(2号)連装砲", Info = "2/2+20.3cm(2号)連装砲(1)/4+20.3cm(2号)連装砲(1)　⇒20.3cm(3号)連装砲", Days = new string[] {"日","月","火"}, ShipName = "妙高"},
            new IATable { Equip = "20.3cm(3号)連装砲", Info = "2/3+20.3cm(3号)連装砲(1)", Days = new string[] {"火","水"}, ShipName = "三隈"},
            new IATable { Equip = "203mm/53 連装砲", Info = "3+20.3cm連装砲(2)/4+20.3cm(2号)連装砲(1)", Days = new string[] {"日","月","火","水"}, ShipName = "Zara due"},
            new IATable { Equip = "35.6cm連装砲", Info = "1/2+35.6cm連装砲(1)/5+35.6cm連装砲(3)　⇒試製35.6cm三連装砲", Days = new string[] {"日","金","土"}, ShipName = "扶桑"},
            new IATable { Equip = "35.6cm連装砲(ダズル迷彩)", Info = "2+35.6cm連装砲(1)/3+35.6cm連装砲(2)", Days = new string[] {"日","月","火","水","土"}, ShipName = "榛名改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "3+35.6cm連装砲(2)/4+35.6cm連装砲(3)", Days = new string[] {"水","木"}, ShipName = "金剛改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "3+35.6cm連装砲(2)/4+35.6cm連装砲(3)", Days = new string[] {"木","金"}, ShipName = "榛名改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "3+35.6cm連装砲(2)/4+35.6cm連装砲(3)", Days = new string[] {"水","木","金","土"}, ShipName = "扶桑改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "3+35.6cm連装砲(2)/4+35.6cm連装砲(3)", Days = new string[] {"日","木","金","土"}, ShipName = "山城改二"},
            new IATable { Equip = "38cm連装砲", Info = "2+35.6cm連装砲(1)/3+35.6cm連装砲(2)/6+41cm連装砲(2)　⇒38cm連装砲改★+3", Days = new string[] {"木","金","土"}, ShipName = "Bismarck"},
            new IATable { Equip = "38cm連装砲改", Info = "3+41cm連装砲(1)/4+41cm連装砲(2)", Days = new string[] {"日","月","火"}, ShipName = "Bismarck"},
            new IATable { Equip = "38.1cm Mk.I連装砲", Info = "3+35.6cm連装砲(2)/3+41cm連装砲(2)/6+25mm単装機銃(2)　⇒38.1cm Mk.I/N連装砲改", Days = new string[] {"日","木","金","土"}, ShipName = "Warspite"},
            new IATable { Equip = "38.1cm Mk.I/N連装砲改", Info = "3+41cm連装砲(1)/4+41cm連装砲(2)", Days = new string[] {"火","水","木","金"}, ShipName = "Warspite"},
            new IATable { Equip = "381mm/50 三連装砲", Info = "2+35.6cm連装砲(1)/3+35.6cm連装砲(2)/7+25mm連装機銃(2)　⇒381mm/50 三連装砲改★+3", Days = new string[] {"火","水","木","金"}, ShipName = "Littorio"},
            new IATable { Equip = "381mm/50 三連装砲", Info = "2+35.6cm連装砲(1)/3+35.6cm連装砲(2)/7+25mm連装機銃(2)　⇒381mm/50 三連装砲改★+3", Days = new string[] {"日","月","土"}, ShipName = "Roma"},
            new IATable { Equip = "381mm/50 三連装砲改", Info = "3+41cm連装砲(1)/4+41cm連装砲(2)", Days = new string[] {"日","月","土"}, ShipName = "Littorio"},
            new IATable { Equip = "381mm/50 三連装砲改", Info = "3+41cm連装砲(1)/4+41cm連装砲(2)", Days = new string[] {"火","水","木","金"}, ShipName = "Roma"},
            new IATable { Equip = "41cm連装砲", Info = "2+41cm連装砲(1)/3+41cm連装砲(2)/10+46cm三連装砲(2)+新型砲熕兵装資材(2)　⇒試製41cm三連装砲", Days = new string[] {"火","金","土"}, ShipName = "長門"},
            new IATable { Equip = "41cm連装砲", Info = "2+41cm連装砲(1)/3+41cm連装砲(2)/10+46cm三連装砲(2)+新型砲熕兵装資材(2)　⇒試製41cm三連装砲", Days = new string[] {"日","月","木"}, ShipName = "陸奥"},
            new IATable { Equip = "試製41cm三連装砲", Info = "4+41cm連装砲(2)/5+41cm連装砲(3)/12+46cm三連装砲(2)+新型砲熕兵装資材(2)　⇒41cm三連装砲改", Days = new string[] {"日","月","水","木"}, ShipName = "長門改"},
            new IATable { Equip = "試製41cm三連装砲", Info = "4+41cm連装砲(2)/5+41cm連装砲(3)/12+46cm三連装砲(2)+新型砲熕兵装資材(2)　⇒41cm三連装砲改", Days = new string[] {"火","水","金","土"}, ShipName = "陸奥改"},
            new IATable { Equip = "41cm三連装砲改", Info = "6+41cm連装砲(2)/7+46cm三連装砲(2)", Days = new string[] {"月","火","水"}, ShipName = "長門改二"},
            new IATable { Equip = "16inch三連装砲 Mk.7", Info = "6+41cm連装砲(3)/8+46cm三連装砲(3)/12+32号対水上電探(2)　⇒16inch三連装砲 Mk.7+GFCS", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "Iowa"},
            new IATable { Equip = "16inch三連装砲 Mk.7+GFCS", Info = "8+22号対水上電探(2)/8+32号対水上電探(2)", Days = new string[] {"日","木","金","土"}, ShipName = "Iowa"},
            new IATable { Equip = "試製46cm連装砲", Info = "3+41cm連装砲(2)/4+41cm連装砲(3)/8+41cm連装砲(4)　⇒46cm三連装砲★+5", Days = new string[] {"日","月"}, ShipName = "大和"},
            new IATable { Equip = "試製46cm連装砲", Info = "3+41cm連装砲(2)/4+41cm連装砲(3)/8+41cm連装砲(4)　⇒46cm三連装砲★+5", Days = new string[] {"火","水"}, ShipName = "武蔵"},
            new IATable { Equip = "46cm三連装砲", Info = "4+46cm三連装砲(1)/5+46cm三連装砲(2)", Days = new string[] {"火","水","木","金","土"}, ShipName = "大和"},
            new IATable { Equip = "46cm三連装砲", Info = "4+46cm三連装砲(1)/5+46cm三連装砲(2)", Days = new string[] {"火","水","木"}, ShipName = "大和改"},
            new IATable { Equip = "46cm三連装砲", Info = "4+46cm三連装砲(1)/5+46cm三連装砲(2)", Days = new string[] {"日","月"}, ShipName = "武蔵"},
            new IATable { Equip = "試製51cm連装砲", Info = "5+46cm三連装砲(2)/7+46cm三連装砲(3)", Days = new string[] {"月","火"}, ShipName = "大和改"},
            new IATable { Equip = "試製51cm連装砲", Info = "5+46cm三連装砲(2)/7+46cm三連装砲(3)", Days = new string[] {"月","水"}, ShipName = "武蔵改"},
            new IATable { Equip = "90mm単装高角砲", Info = "1+10cm連装高角砲(1)/1+10cm連装高角砲(2)", Days = new string[] {"月","火","水","木"}, ShipName = "Littorio"},
            new IATable { Equip = "90mm単装高角砲", Info = "1+10cm連装高角砲(1)/1+10cm連装高角砲(2)", Days = new string[] {"日","木","金","土"}, ShipName = "Roma"},
            new IATable { Equip = "15.2cm単装砲", Info = "1/2+15.2cm単装砲(1)/3+15.2cm単装砲(2)　⇒15.2cm連装砲", Days = new string[] {"日","月","土"}, ShipName = "金剛"},
            new IATable { Equip = "15.2cm単装砲", Info = "1/2+15.2cm単装砲(1)/3+15.2cm単装砲(2)　⇒15.2cm連装砲", Days = new string[] {"月","火","水"}, ShipName = "山城"},
            new IATable { Equip = "15.2cm単装砲", Info = "1/2+15.2cm単装砲(1)/3+15.2cm単装砲(2)　⇒15.2cm連装砲", Days = new string[] {"日","月","火"}, ShipName = "阿賀野"},
            new IATable { Equip = "15.5cm三連装副砲", Info = "2/2+15.5cm三連装副砲(1)/4+15.5cm三連装副砲(2)+新型砲熕兵装資材(1)　⇒15.5cm三連装副砲改", Days = new string[] {"金","土"}, ShipName = "大和"},
            new IATable { Equip = "15.5cm三連装副砲", Info = "2/2+15.5cm三連装副砲(1)/4+15.5cm三連装副砲(2)+新型砲熕兵装資材(1)　⇒15.5cm三連装副砲改", Days = new string[] {"金","土"}, ShipName = "武蔵改"},
            new IATable { Equip = "15.5cm三連装副砲", Info = "2/2+15.5cm三連装副砲(1)/4+15.5cm三連装副砲(2)+新型砲熕兵装資材(1)　⇒15.5cm三連装副砲改", Days = new string[] {"日","金","土"}, ShipName = "武蔵"},
            new IATable { Equip = "15.5cm三連装副砲改", Info = "4+15.5cm三連装副砲(2)/5+15.5cm三連装砲(2)/2+15.5cm三連装砲(1)　⇒15.5cm三連装砲改★+7", Days = new string[] {"金","土"}, ShipName = "大和改"},
            new IATable { Equip = "15.5cm三連装副砲改", Info = "4+15.5cm三連装副砲(2)/5+15.5cm三連装砲(2)/2+15.5cm三連装砲(1)　⇒15.5cm三連装砲改★+7", Days = new string[] {"日","月"}, ShipName = "武蔵改"},
            new IATable { Equip = "OTO 152mm三連装速射砲", Info = "2/3+15.5cm三連装砲(1)", Days = new string[] {"日","火","水","土"}, ShipName = "Littorio"},
            new IATable { Equip = "OTO 152mm三連装速射砲", Info = "2/3+15.5cm三連装砲(1)", Days = new string[] {"日","月","木","金"}, ShipName = "Roma"},
            new IATable { Equip = "15.2cm三連装砲", Info = "6+15.5cm三連装副砲(1)/7+22号対水上電探(2)", Days = new string[] {"月","火","水","木"}, ShipName = "Richelieu"},
            new IATable { Equip = "12.7cm連装高角砲", Info = "2+12.7cm連装高角砲(1)/3+12.7cm連装高角砲(1)/6+10cm連装高角砲(1)　⇒8cm高角砲", Days = new string[] {"金","土"}, ShipName = "摩耶改二"},
            new IATable { Equip = "12.7cm連装高角砲", Info = "2+12.7cm連装高角砲(1)/3+12.7cm連装高角砲(1)/6+10cm連装高角砲(1)　⇒8cm高角砲", Days = new string[] {"日","金","土"}, ShipName = "鈴谷"},
            new IATable { Equip = "12.7cm連装高角砲", Info = "2+12.7cm連装高角砲(1)/3+12.7cm連装高角砲(1)/6+10cm連装高角砲(1)　⇒8cm高角砲", Days = new string[] {"日","月","土"}, ShipName = "熊野"},
            new IATable { Equip = "8cm高角砲", Info = "3+10cm連装高角砲(1)/4+10cm連装高角砲(2)/8+25mm単装機銃(2)　⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"火","水","木"}, ShipName = "鈴谷改二"},
            new IATable { Equip = "8cm高角砲", Info = "3+10cm連装高角砲(1)/4+10cm連装高角砲(2)/8+25mm単装機銃(2)　⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"月","火","水"}, ShipName = "熊野改二"},
            new IATable { Equip = "8cm高角砲", Info = "3+10cm連装高角砲(1)/4+10cm連装高角砲(2)/8+25mm単装機銃(2)　⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"日","木","金","土"}, ShipName = "阿賀野"},
            new IATable { Equip = "8cm高角砲", Info = "3+10cm連装高角砲(1)/4+10cm連装高角砲(2)/8+25mm単装機銃(2)　⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"日","月","金","土"}, ShipName = "能代"},
            new IATable { Equip = "8cm高角砲", Info = "3+10cm連装高角砲(1)/4+10cm連装高角砲(2)/8+25mm単装機銃(2)　⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"日","月","火"}, ShipName = "矢矧"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "4+10cm連装高角砲(2)/6+25mm単装機銃(2)", Days = new string[] {"火","水","木"}, ShipName = "鈴谷改二"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "4+10cm連装高角砲(2)/6+25mm単装機銃(2)", Days = new string[] {"火","水","木"}, ShipName = "矢矧"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "4+10cm連装高角砲(2)/6+25mm単装機銃(2)", Days = new string[] {"火","水","木"}, ShipName = "酒匂"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "4+10cm連装高角砲(2)/6+25mm単装機銃(2)", Days = new string[] {"月","火","水"}, ShipName = "熊野改二"},
            new IATable { Equip = "61cm三連装魚雷", Info = "1/1+61cm三連装魚雷(1)/2+61cm三連装魚雷(2)　⇒61cm三連装(酸素)魚雷", Days = new string[] {"木","金","土" }, ShipName = "吹雪"},
            new IATable { Equip = "61cm三連装魚雷", Info = "1/1+61cm三連装魚雷(1)/2+61cm三連装魚雷(2)　⇒61cm三連装(酸素)魚雷", Days = new string[] {"日","月","火"}, ShipName = "叢雲"},
            new IATable { Equip = "61cm三連装(酸素)魚雷", Info = "1/1+61cm三連装魚雷(1)/3+61cm四連装魚雷(2)　⇒61cm四連装(酸素)魚雷★+5", Days = new string[] {"木","金","土"}, ShipName = "吹雪改二"},
            new IATable { Equip = "61cm四連装魚雷", Info = "1/1+61cm四連装魚雷(1)/3+61cm四連装魚雷(2)　⇒61cm四連装(酸素)魚雷★+3", Days = new string[] {"日","月","火","金","土"}, ShipName = ""},
            new IATable { Equip = "61cm四連装(酸素)魚雷", Info = "1/2+61cm四連装(酸素)魚雷(1)/5+61cm四連装(酸素)魚雷(3)　⇒61cm五連装(酸素)魚雷", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "大井"},
            new IATable { Equip = "61cm四連装(酸素)魚雷", Info = "1/2+61cm四連装(酸素)魚雷(1)/5+61cm四連装(酸素)魚雷(3)　⇒61cm五連装(酸素)魚雷", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "北上"},
            new IATable { Equip = "61cm五連装(酸素)魚雷", Info = "3/3+61cm五連装(酸素)魚雷(1)", Days = new string[] {"水","木"}, ShipName = "島風"},
            new IATable { Equip = "試製61cm六連装(酸素)魚雷", Info = "5+61cm四連装(酸素)魚雷(2)/6+61cm五連装(酸素)魚雷(1)", Days = new string[] {"水","木","金","土"}, ShipName = "初月"},
            new IATable { Equip = "試製61cm六連装(酸素)魚雷", Info = "5+61cm四連装(酸素)魚雷(2)/6+61cm五連装(酸素)魚雷(1)", Days = new string[] {"日","土"}, ShipName = "島風"},
            new IATable { Equip = "九六式艦戦", Info = "1+九六式艦戦(1)/1+7.7mm機銃(1)/2+九六式艦戦(2)　⇒零式艦戦21型★+3", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "鳳翔"},
            new IATable { Equip = "零式艦戦21型", Info = "2+零式艦戦21型(1)/2+零式艦戦21型(2)/3+7.7mm機銃(2)　⇒零式艦戦32型★+3", Days = new string[] {"木","金","土"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦21型", Info = "2+零式艦戦21型(1)/2+零式艦戦21型(2)/3+7.7mm機銃(2)　⇒零式艦戦32型★+3", Days = new string[] {"日","月","火"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦21型(熟練)", Info = "2+零式艦戦21型(2)/2+零式艦戦21型(3)/3+7.7mm機銃(3)　⇒零式艦戦32型(熟練)★+3", Days = new string[] {"木","金","土"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦21型(熟練)", Info = "2+零式艦戦21型(2)/2+零式艦戦21型(3)/3+7.7mm機銃(3)　⇒零式艦戦32型(熟練)★+3", Days = new string[] {"日","月","火"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦32型", Info = "2+零式艦戦21型(1)/3+零式艦戦21型(2)/4+零式艦戦32型(1)　⇒零式艦戦52型★+3", Days = new string[] {"日","月"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦32型", Info = "2+零式艦戦21型(1)/3+零式艦戦21型(2)/4+零式艦戦32型(1)　⇒零式艦戦52型★+3", Days = new string[] {"水","木"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦32型(熟練)", Info = "2+零式艦戦21型(2)/3+零式艦戦21型(3)/4+零式艦戦32型(2)　⇒零式艦戦52型(熟練)★+3", Days = new string[] {"日","月"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦32型(熟練)", Info = "2+零式艦戦21型(2)/3+零式艦戦21型(3)/4+零式艦戦32型(2)　⇒零式艦戦52型(熟練)★+3", Days = new string[] {"水","木"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦52型", Info = "3+零式艦戦52型(1)/3+零式艦戦52型(2)", Days = new string[] {"木","金","土"}, ShipName = "翔鶴"},
            new IATable { Equip = "零式艦戦52型", Info = "3+零式艦戦52型(1)/3+零式艦戦52型(2)", Days = new string[] {"日","月","水"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零式艦戦52型(熟練)", Info = "3+零式艦戦52型(2)/4+零式艦戦52型(3)", Days = new string[] {"木","金","土"}, ShipName = "翔鶴"},
            new IATable { Equip = "零式艦戦52型(熟練)", Info = "3+零式艦戦52型(2)/4+零式艦戦52型(3)", Days = new string[] {"日","月","水"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零戦52型丙(六〇一空)", Info = "3+零式艦戦52型(2)/4+天山(2)", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "大鳳"},
            new IATable { Equip = "零戦52型丙(六〇一空)", Info = "3+零式艦戦52型(2)/4+天山(2)", Days = new string[] {"水","木","金","土"}, ShipName = "雲龍"},
            new IATable { Equip = "零戦52型丙(付岩井小隊)", Info = "3+零式艦戦52型(2)/4+零式艦戦52型(3)", Days = new string[] {"火","木"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零戦52型甲(付岩本小隊)", Info = "3+零式艦戦52型(2)/4+零式艦戦52型(3)", Days = new string[] {"金","土"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零式艦戦53型(岩本隊)", Info = "3+零式艦戦52型(2)/4+零式艦戦52型(3)", Days = new string[] {"金","土"}, ShipName = "瑞鶴"},
            new IATable { Equip = "F4F-3", Info = "2/2+九六式艦戦(1)/3+12.7mm単装機銃(2)　⇒F4F-4", Days = new string[] {"日","水","木","金","土"}, ShipName = "Saratoga"},
            new IATable { Equip = "F4F-3", Info = "2/2+九六式艦戦(1)/3+12.7mm単装機銃(2)　⇒F4F-4", Days = new string[] {"金","土"}, ShipName = "Saratoga改"},
            new IATable { Equip = "F4F-3", Info = "2/2+九六式艦戦(1)/3+12.7mm単装機銃(2)　⇒F4F-4", Days = new string[] {"火","水"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "F4F-4", Info = "3+零式艦戦21型(1)/3+零式艦戦32型(1)/6+零式艦戦52型(2)　⇒F6F-3", Days = new string[] {"月","火"}, ShipName = "Saratoga"},
            new IATable { Equip = "F4F-4", Info = "3+零式艦戦21型(1)/3+零式艦戦32型(1)/6+零式艦戦52型(2)　⇒F6F-3", Days = new string[] {"月","火","水"}, ShipName = "Saratoga改"},
            new IATable { Equip = "F4F-4", Info = "3+零式艦戦21型(1)/3+零式艦戦32型(1)/6+零式艦戦52型(2)　⇒F6F-3", Days = new string[] {"月","木"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "F6F-3", Info = "4+零式艦戦52型(2)/6+紫電改二(1)/8+紫電改二(2)　⇒F6F-5", Days = new string[] {"火","水","木"}, ShipName = "Saratoga改"},
            new IATable { Equip = "F6F-3", Info = "4+零式艦戦52型(2)/6+紫電改二(1)/8+紫電改二(2)　⇒F6F-5", Days = new string[] {"火","水","木"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "F6F-5", Info = "6+紫電改二(2)/8+烈風(1)", Days = new string[] {"火","水","木"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "零式艦戦62型(爆戦)", Info = "3+零式艦戦52型(2)/4+彗星(2)/6+烈風(1)　⇒零式艦戦63型(爆戦)(鈴谷航改二)", Days = new string[] {"日","月"}, ShipName = "翔鶴"},
            new IATable { Equip = "零式艦戦62型(爆戦)", Info = "3+零式艦戦52型(2)/4+彗星(2)/6+烈風(1)　⇒零式艦戦63型(爆戦)(鈴谷航改二)", Days = new string[] {"日","月"}, ShipName = "鈴谷航改二"},
            new IATable { Equip = "零式艦戦62型(爆戦)", Info = "3+零式艦戦52型(2)/4+彗星(2)/6+烈風(1)　⇒零式艦戦63型(爆戦)(鈴谷航改二)", Days = new string[] {"日","金","土"}, ShipName = "隼鷹"},
            new IATable { Equip = "零戦62型(爆戦/岩井隊)", Info = "3+零式艦戦52型(2)/4+彗星(2)", Days = new string[] {"火","木"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零式艦戦63型(爆戦)", Info = "4+零式艦戦52型(3)/5+烈風(1)", Days = new string[] {"月","火","水","木"}, ShipName = "鈴谷航改二"},
            new IATable { Equip = "零式艦戦63型(爆戦)", Info = "4+零式艦戦52型(3)/5+烈風(1)", Days = new string[] {"火","水","木","金"}, ShipName = "熊野航改二"},
            new IATable { Equip = "試製景雲(艦偵型)", Info = "6+流星(1)/7+烈風(1)/10+ネ式エンジン(1)　⇒噴式景雲改", Days = new string[] {"日","金","土"}, ShipName = "翔鶴改二甲"},
            new IATable { Equip = "試製景雲(艦偵型)", Info = "6+流星(1)/7+烈風(1)/10+ネ式エンジン(1)　⇒噴式景雲改", Days = new string[] {"日","月","火"}, ShipName = "瑞鶴改二甲"},
            new IATable { Equip = "零式水上偵察機", Info = "2+零式水上偵察機(1)/3+零式水上偵察機(2)/5+零式艦戦21型(3)　⇒二式水戦改", Days = new string[] {"金","土"}, ShipName = "千歳甲"},
            new IATable { Equip = "零式水上偵察機", Info = "2+零式水上偵察機(1)/3+零式水上偵察機(2)/5+零式艦戦21型(3)　⇒二式水戦改", Days = new string[] {"水","木"}, ShipName = "千代田甲"},
            new IATable { Equip = "零式水上偵察機", Info = "2+零式水上偵察機(1)/3+零式水上偵察機(2)/5+零式艦戦21型(3)　⇒二式水戦改", Days = new string[] {"日","木","金","土"}, ShipName = "秋津洲改"},
            new IATable { Equip = "零式水上偵察機", Info = "2+零式水上偵察機(1)/3+零式水上偵察機(2)/5+零式艦戦21型(3)　⇒二式水戦改", Days = new string[] {"月","火","水"}, ShipName = "瑞穂"},
            new IATable { Equip = "零式水上観測機", Info = "3+瑞雲(1)/4+零式水上観測機(1)", Days = new string[] {"木","金","土"}, ShipName = "武蔵"},
            new IATable { Equip = "零式水上観測機", Info = "3+瑞雲(1)/4+零式水上観測機(1)", Days = new string[] {"月","火","水"}, ShipName = "瑞穂"},
            new IATable { Equip = "九八式水上偵察機(夜偵)", Info = "3+零式水上偵察機(1)/4+零式水上偵察機(2)", Days = new string[] {"日","月","木","金","土"}, ShipName = "川内改二"},
            new IATable { Equip = "Ro.43水偵", Info = "1+零式水上偵察機(1)/2+瑞雲(1)/3+零式水上偵察機(2)　⇒Ro.44水上戦闘機", Days = new string[] {"日","土"}, ShipName = "Italia"},
            new IATable { Equip = "Ro.43水偵", Info = "1+零式水上偵察機(1)/2+瑞雲(1)/3+零式水上偵察機(2)　⇒Ro.44水上戦闘機", Days = new string[] {"火","水"}, ShipName = "Roma改"},
            new IATable { Equip = "Ro.43水偵", Info = "1+零式水上偵察機(1)/2+瑞雲(1)/3+零式水上偵察機(2)　⇒Ro.44水上戦闘機", Days = new string[] {"月","火","水","木","金"}, ShipName = "Zara改"},
            new IATable { Equip = "Ro.43水偵", Info = "1+零式水上偵察機(1)/2+瑞雲(1)/3+零式水上偵察機(2)　⇒Ro.44水上戦闘機", Days = new string[] {"木","金","土"}, ShipName = "Zara due"},
            new IATable { Equip = "二式水戦改", Info = "5+零式艦戦21型(2)/7+零式水上偵察機(2)/9+瑞雲(2)　⇒強風改", Days = new string[] {"日","金","土"}, ShipName = "瑞穂"},
            new IATable { Equip = "二式水戦改(熟練)", Info = "7+零式艦戦32型(2)/8+瑞雲(3)", Days = new string[] {"日","金","土"}, ShipName = "瑞穂"},
            new IATable { Equip = "強風改", Info = "6+紫電改二(1)/7+紫電改二(1)", Days = new string[] {"火","水","木"}, ShipName = "瑞穂"},
            new IATable { Equip = "強風改", Info = "6+紫電改二(1)/7+紫電改二(1)", Days = new string[] {"月","火","水","木"}, ShipName = "鈴谷改二"},
            new IATable { Equip = "Ro.44水上戦闘機", Info = "3+瑞雲(1)/5+瑞雲(2)/8+Ro.44水上戦闘機(1)　⇒Ro.44水上戦闘機bis", Days = new string[] {"日","木","金","土"}, ShipName = "Zara due"},
            new IATable { Equip = "Ro.44水上戦闘機bis", Info = "4+瑞雲(2)/6+Ro.44水上戦闘機(1)", Days = new string[] {"金","土"}, ShipName = "Zara due"},
            new IATable { Equip = "瑞雲", Info = "3+瑞雲(1)/5+瑞雲(1)/7+瑞雲(2)+熟練搭乗員(1)　⇒瑞雲(六三四空)", Days = new string[] {"日","金","土"}, ShipName = "伊勢改"},
            new IATable { Equip = "瑞雲", Info = "3+瑞雲(1)/5+瑞雲(1)/7+瑞雲(2)+熟練搭乗員(1)　⇒瑞雲(六三四空)", Days = new string[] {"日","金","土"}, ShipName = "日向改"},
            new IATable { Equip = "瑞雲", Info = "3+瑞雲(1)/5+瑞雲(1)/7+瑞雲(2)+熟練搭乗員(1)　⇒瑞雲(六三四空)", Days = new string[] {"月","火","水","木"}, ShipName = "最上改"},
            new IATable { Equip = "瑞雲(六三四空)", Info = "5+瑞雲(1)/6+瑞雲(2)", Days = new string[] {"日","金","土"}, ShipName = "伊勢改"},
            new IATable { Equip = "瑞雲(六三四空)", Info = "5+瑞雲(1)/6+瑞雲(2)", Days = new string[] {"日","金","土"}, ShipName = "日向改"},
            new IATable { Equip = "瑞雲(六三四空/熟練)", Info = "6+瑞雲(2)/7+瑞雲(3)", Days = new string[] {"日","金","土"}, ShipName = "日向改"},
            new IATable { Equip = "13号対空電探", Info = "2/3+13号対空電探(1)/5+21号対空電探(1)　⇒13号対空電探改", Days = new string[] {"日","月","金","土"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "13号対空電探", Info = "2/3+13号対空電探(1)/5+21号対空電探(1)　⇒13号対空電探改", Days = new string[] {"日","木","金","土"}, ShipName = "時雨改二"},
            new IATable { Equip = "13号対空電探", Info = "2/3+13号対空電探(1)/5+21号対空電探(1)　⇒13号対空電探改", Days = new string[] {"火","水","木"}, ShipName = "秋月"},
            new IATable { Equip = "13号対空電探", Info = "2/3+13号対空電探(1)/5+21号対空電探(1)　⇒13号対空電探改", Days = new string[] {"月","火","水"}, ShipName = "照月"},
            new IATable { Equip = "13号対空電探改", Info = "3+13号対空電探(1)/4+13号対空電探(2)", Days = new string[] {"日","金","土"}, ShipName = "初霜改二"},
            new IATable { Equip = "13号対空電探改", Info = "3+13号対空電探(1)/4+13号対空電探(2)", Days = new string[] {"日","月","火","水"}, ShipName = "雪風"},
            new IATable { Equip = "13号対空電探改", Info = "3+13号対空電探(1)/4+13号対空電探(2)", Days = new string[] {"木","金","土"}, ShipName = "磯風改"},
            new IATable { Equip = "22号対水上電探", Info = "2+22号対水上電探(1)/3+22号対水上電探(2)/8+22号対水上電探(3)　⇒22号対水上電探改四", Days = new string[] {"日","月","金","土"}, ShipName = "日向"},
            new IATable { Equip = "22号対水上電探", Info = "2+22号対水上電探(1)/3+22号対水上電探(2)/8+22号対水上電探(3)　⇒22号対水上電探改四", Days = new string[] {"月"}, ShipName = "日向改"},
            new IATable { Equip = "22号対水上電探", Info = "2+22号対水上電探(1)/3+22号対水上電探(2)/8+22号対水上電探(3)　⇒22号対水上電探改四", Days = new string[] {"月","火","金","土"}, ShipName = "夕雲"},
            new IATable { Equip = "22号対水上電探", Info = "2+22号対水上電探(1)/3+22号対水上電探(2)/8+22号対水上電探(3)　⇒22号対水上電探改四", Days = new string[] {"木","金","土"}, ShipName = "島風"},
            new IATable { Equip = "22号対水上電探改四", Info = "3+22号対水上電探(1)/4+22号対水上電探改四(1)", Days = new string[] {"火","水","木","金"}, ShipName = "金剛改二"},
            new IATable { Equip = "22号対水上電探改四", Info = "3+22号対水上電探(1)/4+22号対水上電探改四(1)", Days = new string[] {"日","木","金","土"}, ShipName = "妙高改二"},
            new IATable { Equip = "22号対水上電探改四", Info = "3+22号対水上電探(1)/4+22号対水上電探改四(1)", Days = new string[] {"日","月","金","土"}, ShipName = "羽黒改二"},
            new IATable { Equip = "21号対空電探", Info = "2/3+21号対空電探(1)/5+21号対空電探(2)　⇒21号対空電探改", Days = new string[] {"日","月","金","土"}, ShipName = "伊勢"},
            new IATable { Equip = "21号対空電探", Info = "2/3+21号対空電探(1)/5+21号対空電探(2)　⇒21号対空電探改", Days = new string[] {"月"}, ShipName = "伊勢改"},
            new IATable { Equip = "21号対空電探", Info = "2/3+21号対空電探(1)/5+21号対空電探(2)　⇒21号対空電探改", Days = new string[] {"水","木","金","土"}, ShipName = "日向"},
            new IATable { Equip = "21号対空電探", Info = "2/3+21号対空電探(1)/5+21号対空電探(2)　⇒21号対空電探改", Days = new string[] {"水","木"}, ShipName = "日向改"},
            new IATable { Equip = "21号対空電探改", Info = "2+21号対空電探(1)/4+21号対空電探(2)", Days = new string[] {"日","木"}, ShipName = "大和"},
            new IATable { Equip = "21号対空電探改", Info = "2+21号対空電探(1)/4+21号対空電探(2)", Days = new string[] {"火","水","木"}, ShipName = "武蔵"},
            new IATable { Equip = "32号対水上電探", Info = "3+22号対水上電探(1)/4+22号対水上電探(2)/10+32号対水上電探(1)　⇒32号対水上電探改", Days = new string[] {"水","木","金","土"}, ShipName = "伊勢"},
            new IATable { Equip = "32号対水上電探", Info = "3+22号対水上電探(1)/4+22号対水上電探(2)/10+32号対水上電探(1)　⇒32号対水上電探改", Days = new string[] {"日","月","火"}, ShipName = "日向"},
            new IATable { Equip = "32号対水上電探", Info = "3+22号対水上電探(1)/4+22号対水上電探(2)/10+32号対水上電探(1)　⇒32号対水上電探改", Days = new string[] {"月","火"}, ShipName = "日向改"},
            new IATable { Equip = "32号対水上電探改", Info = "5+22号対水上電探(3)/7+32号対水上電探(1)", Days = new string[] {"日","月","火"}, ShipName = "伊勢"},
            new IATable { Equip = "32号対水上電探改", Info = "5+22号対水上電探(3)/7+32号対水上電探(1)", Days = new string[] {"水","木","金","土"}, ShipName = "日向"},
            new IATable { Equip = "32号対水上電探改", Info = "5+22号対水上電探(3)/7+32号対水上電探(1)", Days = new string[] {"水","木"}, ShipName = "日向改"},
            new IATable { Equip = "九三式水中聴音機", Info = "1/2+九三式水中聴音機(1)/3+九三式水中聴音機(2)　⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機(1)/6+三式水中探信儀(2)　⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"月","木","金"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "九三式水中聴音機", Info = "1/2+九三式水中聴音機(1)/3+九三式水中聴音機(2)　⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機(1)/6+三式水中探信儀(2)　⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"日","金","土"}, ShipName = "夕張"},
            new IATable { Equip = "九三式水中聴音機", Info = "1/2+九三式水中聴音機(1)/3+九三式水中聴音機(2)　⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機(1)/6+三式水中探信儀(2)　⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"日","金","土"}, ShipName = "香取改"},
            new IATable { Equip = "九三式水中聴音機", Info = "1/2+九三式水中聴音機(1)/3+九三式水中聴音機(2)　⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機(1)/6+三式水中探信儀(2)　⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"日","木","金","土"}, ShipName = "時雨改二"},
            new IATable { Equip = "三式水中探信儀", Info = "2/3+三式水中探信儀(1)", Days = new string[] {"日","火","水"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "三式水中探信儀", Info = "2/3+三式水中探信儀(1)", Days = new string[] {"火","水"}, ShipName = "夕張"},
            new IATable { Equip = "四式水中聴音機", Info = "3+九三式水中聴音機(2)/4+四式水中聴音機(1)", Days = new string[] {"木","金","土"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "四式水中聴音機", Info = "3+九三式水中聴音機(2)/4+四式水中聴音機(1)", Days = new string[] {"月","火"}, ShipName = "香取改"},
            new IATable { Equip = "四式水中聴音機", Info = "3+九三式水中聴音機(2)/4+四式水中聴音機(1)", Days = new string[] {"日"}, ShipName = "秋月"},
            new IATable { Equip = "四式水中聴音機", Info = "3+九三式水中聴音機(2)/4+四式水中聴音機(1)", Days = new string[] {"水"}, ShipName = "照月"},
            new IATable { Equip = "九四式爆雷投射機", Info = "1/1+九四式爆雷投射機(1)/3+九四式爆雷投射機(2)　⇒三式爆雷投射機★+3", Days = new string[] {"水","木"}, ShipName = ""},
            new IATable { Equip = "三式爆雷投射機", Info = "2/2+三式爆雷投射機(1)", Days = new string[] {"水","木"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "九五式爆雷", Info = "1/2+九五式爆雷(1)/3+九五式爆雷(2)　⇒二式爆雷", Days = new string[] {"火","水","木"}, ShipName = "那珂改二"},
            new IATable { Equip = "九五式爆雷", Info = "1/2+九五式爆雷(1)/3+九五式爆雷(2)　⇒二式爆雷", Days = new string[] {"日","木","金","土"}, ShipName = "神風"},
            new IATable { Equip = "九五式爆雷", Info = "1/2+九五式爆雷(1)/3+九五式爆雷(2)　⇒二式爆雷", Days = new string[] {"月","火","水","木"}, ShipName = "占守"},
            new IATable { Equip = "九五式爆雷", Info = "1/2+九五式爆雷(1)/3+九五式爆雷(2)　⇒二式爆雷", Days = new string[] {"水","木","金","土"}, ShipName = "択捉"},
            new IATable { Equip = "九一式徹甲弾", Info = "1/1+九一式徹甲弾(1)/4+九一式徹甲弾(3)　⇒一式徹甲弾", Days = new string[] {"水","木","金","土"}, ShipName = "比叡"},
            new IATable { Equip = "九一式徹甲弾", Info = "1/1+九一式徹甲弾(1)/4+九一式徹甲弾(3)　⇒一式徹甲弾", Days = new string[] {"日","月","金","土"}, ShipName = "霧島"},
            new IATable { Equip = "一式徹甲弾", Info = "1+九一式徹甲弾(2)/2+一式徹甲弾(1)", Days = new string[] {"日","金","土"}, ShipName = "金剛"},
            new IATable { Equip = "一式徹甲弾", Info = "1+九一式徹甲弾(2)/2+一式徹甲弾(1)", Days = new string[] {"月","火","水"}, ShipName = "榛名"},
            new IATable { Equip = "25mm単装機銃", Info = "1/1+25mm単装機銃(1)/1+25mm単装機銃(1)　⇒25mm連装機銃★+5", Days = new string[] {"木"}, ShipName = "鬼怒"},
            new IATable { Equip = "25mm単装機銃", Info = "1/1+25mm単装機銃(1)/1+25mm単装機銃(1)　⇒25mm連装機銃★+5", Days = new string[] {"日","金","土"}, ShipName = "皐月"},
            new IATable { Equip = "25mm単装機銃", Info = "1/1+25mm単装機銃(1)/1+25mm単装機銃(1)　⇒25mm連装機銃★+5", Days = new string[] {"水","木","金","土"}, ShipName = "文月"},
            new IATable { Equip = "25mm連装機銃", Info = "1/1+25mm連装機銃(1)/1+25mm連装機銃(1)　⇒25mm三連装機銃★+3", Days = new string[] {"日","土"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "25mm連装機銃", Info = "1/1+25mm連装機銃(1)/1+25mm連装機銃(1)　⇒25mm三連装機銃★+3", Days = new string[] {"水"}, ShipName = "鬼怒"},
            new IATable { Equip = "25mm連装機銃", Info = "1/1+25mm連装機銃(1)/1+25mm連装機銃(1)　⇒25mm三連装機銃★+3", Days = new string[] {"月","火"}, ShipName = "皐月"},
            new IATable { Equip = "25mm連装機銃", Info = "1/1+25mm連装機銃(1)/1+25mm連装機銃(1)　⇒25mm三連装機銃★+3", Days = new string[] {"日","月","火"}, ShipName = "文月"},
            new IATable { Equip = "25mm三連装機銃", Info = "1/1+25mm三連装機銃(1)/3+25mm三連装機銃(5)　⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"火","水","木"}, ShipName = "摩耶"},
            new IATable { Equip = "25mm三連装機銃", Info = "1/1+25mm三連装機銃(1)/3+25mm三連装機銃(5)　⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"日","月","火","水","木"}, ShipName = "摩耶改二"},
            new IATable { Equip = "25mm三連装機銃", Info = "1/1+25mm三連装機銃(1)/3+25mm三連装機銃(5)　⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"月","火","水"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "25mm三連装機銃", Info = "1/1+25mm三連装機銃(1)/3+25mm三連装機銃(5)　⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"月","火"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "25mm三連装機銃", Info = "1/1+25mm三連装機銃(1)/3+25mm三連装機銃(5)　⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"水","木"}, ShipName = "皐月改二"},
            new IATable { Equip = "25mm三連装機銃 集中配備", Info = "3+25mm三連装機銃(3)/6+25mm三連装機銃(5)", Days = new string[] {"火","水","木"}, ShipName = "摩耶改二"},
            new IATable { Equip = "25mm三連装機銃 集中配備", Info = "3+25mm三連装機銃(3)/6+25mm三連装機銃(5)", Days = new string[] {"日","金","土"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "91式高射装置", Info = "1/2+12.7cm連装高角砲(1)/4+10cm連装高角砲(2)　⇒94式高射装置", Days = new string[] {"日","月","金","土"}, ShipName = "摩耶"},
            new IATable { Equip = "91式高射装置", Info = "1/2+12.7cm連装高角砲(1)/4+10cm連装高角砲(2)　⇒94式高射装置", Days = new string[] {"日","月","金","土"}, ShipName = "秋月"},
            new IATable { Equip = "91式高射装置", Info = "1/2+12.7cm連装高角砲(1)/4+10cm連装高角砲(2)　⇒94式高射装置", Days = new string[] {"日","木","金","土"}, ShipName = "照月"},
            new IATable { Equip = "94式高射装置", Info = "2/3+10cm連装高角砲(1)/5+10cm連装高角砲(2)　⇒10cm高角砲+高射装置(秋月/照月/初月/吹雪改二)\n2/3+12.7cm連装高角砲(1)/5+12.7cm連装高角砲(2)　⇒12.7cm高角砲+高射装置(摩耶改二)", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "秋月"},
            new IATable { Equip = "94式高射装置", Info = "2/3+10cm連装高角砲(1)/5+10cm連装高角砲(2)　⇒10cm高角砲+高射装置(秋月/照月/初月/吹雪改二)\n2/3+12.7cm連装高角砲(1)/5+12.7cm連装高角砲(2)　⇒12.7cm高角砲+高射装置(摩耶改二)", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "照月"},
            new IATable { Equip = "94式高射装置", Info = "2/3+10cm連装高角砲(1)/5+10cm連装高角砲(2)　⇒10cm高角砲+高射装置(秋月/照月/初月/吹雪改二)\n2/3+12.7cm連装高角砲(1)/5+12.7cm連装高角砲(2)　⇒12.7cm高角砲+高射装置(摩耶改二)", Days = new string[] {"日","金","土"}, ShipName = "初月"},
            new IATable { Equip = "94式高射装置", Info = "2/3+10cm連装高角砲(1)/5+10cm連装高角砲(2)　⇒10cm高角砲+高射装置(秋月/照月/初月/吹雪改二)\n2/3+12.7cm連装高角砲(1)/5+12.7cm連装高角砲(2)　⇒12.7cm高角砲+高射装置(摩耶改二)", Days = new string[] {"日","木","金","土"}, ShipName = "吹雪改二"},
            new IATable { Equip = "94式高射装置", Info = "2/3+10cm連装高角砲(1)/5+10cm連装高角砲(2)　⇒10cm高角砲+高射装置(秋月/照月/初月/吹雪改二)\n2/3+12.7cm連装高角砲(1)/5+12.7cm連装高角砲(2)　⇒12.7cm高角砲+高射装置(摩耶改二)", Days = new string[] {"日","木","金","土"}, ShipName = "摩耶改二"},
            new IATable { Equip = "大発動艇", Info = "1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/3+12.7mm単装機銃(3)　⇒大発動艇(八九式中戦車＆陸戦隊)(阿武隈改二/皐月改二/あきつ丸)\n1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/6+大発動艇(4)　⇒特大発動艇(鬼怒改二)", Days = new string[] {"日","月","金","土"}, ShipName = "阿武隈改二"},
            new IATable { Equip = "大発動艇", Info = "1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/3+12.7mm単装機銃(3)　⇒大発動艇(八九式中戦車＆陸戦隊)(阿武隈改二/皐月改二/あきつ丸)\n1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/6+大発動艇(4)　⇒特大発動艇(鬼怒改二)", Days = new string[] {"日","月","火","水"}, ShipName = "皐月改二"},
            new IATable { Equip = "大発動艇", Info = "1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/3+12.7mm単装機銃(3)　⇒大発動艇(八九式中戦車＆陸戦隊)(阿武隈改二/皐月改二/あきつ丸)\n1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/6+大発動艇(4)　⇒特大発動艇(鬼怒改二)", Days = new string[] {"日","水","木","金","土"}, ShipName = "あきつ丸"},
            new IATable { Equip = "大発動艇", Info = "1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/3+12.7mm単装機銃(3)　⇒大発動艇(八九式中戦車＆陸戦隊)(阿武隈改二/皐月改二/あきつ丸)\n1+ドラム缶(輸送用)(1)/2+7.7mm機銃(1)/6+大発動艇(4)　⇒特大発動艇(鬼怒改二)", Days = new string[] {"日","木","金","土"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "大発動艇(八九式中戦車&陸戦隊)", Info = "3+25mm単装機銃(1)/3+12cm30連装噴進砲(2)/5+7.7mm機銃(3)　⇒特二式内火艇", Days = new string[] {"火","水","木"}, ShipName = "阿武隈改二"},
            new IATable { Equip = "大発動艇(八九式中戦車&陸戦隊)", Info = "3+25mm単装機銃(1)/3+12cm30連装噴進砲(2)/5+7.7mm機銃(3)　⇒特二式内火艇", Days = new string[] {"木","金","土"}, ShipName = "皐月改二"},
            new IATable { Equip = "大発動艇(八九式中戦車&陸戦隊)", Info = "3+25mm単装機銃(1)/3+12cm30連装噴進砲(2)/5+7.7mm機銃(3)　⇒特二式内火艇", Days = new string[] {"日","月","金","土"}, ShipName = "あきつ丸"},
            new IATable { Equip = "特大発動艇", Info = "2+ドラム缶(輸送用)(2)/4+大発動艇(1)", Days = new string[] {"日","月","金","土"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "特大発動艇", Info = "2+ドラム缶(輸送用)(2)/4+大発動艇(1)", Days = new string[] {"火","水","木"}, ShipName = "あきつ丸"},
            new IATable { Equip = "特二式内火艇", Info = "3+7.7mm機銃(2)/4+12.7mm単装機銃(3)", Days = new string[] {"水","木","金","土"}, ShipName = "伊8"},
            new IATable { Equip = "特二式内火艇", Info = "3+7.7mm機銃(2)/4+12.7mm単装機銃(3)", Days = new string[] {"日","月","金","土"}, ShipName = "伊58"},
            new IATable { Equip = "特二式内火艇", Info = "3+7.7mm機銃(2)/4+12.7mm単装機銃(3)", Days = new string[] {"月","火","水","木"}, ShipName = "伊401"},
            new IATable { Equip = "探照灯", Info = "2/2+探照灯(1)/3+熟練見張員(1)　⇒96式150cm探照灯", Days = new string[] {"月","火","水"}, ShipName = "青葉"},
            new IATable { Equip = "探照灯", Info = "2/2+探照灯(1)/3+熟練見張員(1)　⇒96式150cm探照灯", Days = new string[] {"月","火","水"}, ShipName = "綾波"},
            new IATable { Equip = "探照灯", Info = "2/2+探照灯(1)/3+熟練見張員(1)　⇒96式150cm探照灯", Days = new string[] {"日","金","土"}, ShipName = "神通"},
            new IATable { Equip = "探照灯", Info = "2/2+探照灯(1)/3+熟練見張員(1)　⇒96式150cm探照灯", Days = new string[] {"木","金","土"}, ShipName = "暁"},
            new IATable { Equip = "96式150cm探照灯", Info = "3+探照灯(1)/3+探照灯(1)", Days = new string[] {"日","月","金","土"}, ShipName = "比叡"},
            new IATable { Equip = "96式150cm探照灯", Info = "3+探照灯(1)/3+探照灯(1)", Days = new string[] {"火","水","木","金"}, ShipName = "霧島"},
            new IATable { Equip = "増設バルジ(中型艦)", Info = "4+増設バルジ(中型艦)(1)/6+増設バルジ(中型艦)(2)/8+増設バルジ(中型艦)(3)　⇒艦本新設計 増設バルジ(中型艦)", Days = new string[] {"月","火","水"}, ShipName = "Zara due"},
            new IATable { Equip = "増設バルジ(中型艦)", Info = "4+増設バルジ(中型艦)(1)/6+増設バルジ(中型艦)(2)/8+増設バルジ(中型艦)(3)　⇒艦本新設計 増設バルジ(中型艦)", Days = new string[] {"月","火","水","木"}, ShipName = "酒匂"},
            new IATable { Equip = "増設バルジ(中型艦)", Info = "4+増設バルジ(中型艦)(1)/6+増設バルジ(中型艦)(2)/8+増設バルジ(中型艦)(3)　⇒艦本新設計 増設バルジ(中型艦)", Days = new string[] {"日","月","火","水"}, ShipName = "Верный"},
            new IATable { Equip = "艦本新設計 増設バルジ(中型艦)", Info = "6+増設バルジ(中型艦)(2)/8+増設バルジ(中型艦)(3)", Days = new string[] {"火","水","木"}, ShipName = "Zara due"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "4+増設バルジ(中型艦)(2)/6+増設バルジ(大型艦)(1)/8+増設バルジ(大型艦)(2)　⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"木","金","土"}, ShipName = "長門"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "4+増設バルジ(中型艦)(2)/6+増設バルジ(大型艦)(1)/8+増設バルジ(大型艦)(2)　⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"木","金","土"}, ShipName = "武蔵"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "4+増設バルジ(中型艦)(2)/6+増設バルジ(大型艦)(1)/8+増設バルジ(大型艦)(2)　⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"水","木","金"}, ShipName = "陸奥"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "4+増設バルジ(中型艦)(2)/6+増設バルジ(大型艦)(1)/8+増設バルジ(大型艦)(2)　⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"水","木","金"}, ShipName = "大和"},
            new IATable { Equip = "艦本新設計 増設バルジ(大型艦)", Info = "6+増設バルジ(大型艦)(1)/8+増設バルジ(大型艦)(2)", Days = new string[] {"日","土"}, ShipName = "大和"},
            new IATable { Equip = "艦本新設計 増設バルジ(大型艦)", Info = "6+増設バルジ(大型艦)(1)/8+増設バルジ(大型艦)(2)", Days = new string[] {"日","火"}, ShipName = "武蔵"},
            new IATable { Equip = "強化型艦本式缶", Info = "5+改良型艦本式タービン(1)/7+強化型艦本式缶(1)/8+強化型艦本式缶(2)　⇒新型高温高圧缶", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "天津風"},
            new IATable { Equip = "強化型艦本式缶", Info = "5+改良型艦本式タービン(1)/7+強化型艦本式缶(1)/8+強化型艦本式缶(2)　⇒新型高温高圧缶", Days = new string[] {"火","水"}, ShipName = "島風"},
            new IATable { Equip = "新型高温高圧缶", Info = "8+改良型艦本式タービン(2)/9+強化型艦本式缶(2)", Days = new string[] {"火","水","木"}, ShipName = "天津風改"},
            new IATable { Equip = "新型高温高圧缶", Info = "8+改良型艦本式タービン(2)/9+強化型艦本式缶(2)", Days = new string[] {"月","火","金"}, ShipName = "島風"},
            new IATable { Equip = "潜水艦搭載電探&水防式望遠鏡", Info = "7+22号対水上電探(2)/8+熟練見張員(1)", Days = new string[] {"月","火","水","木"}, ShipName = "伊401"},
            new IATable { Equip = "戦闘糧食", Info = "0+戦闘糧食(1)/1/0+戦闘糧食(1)　⇒戦闘糧食(特別なおにぎり)", Days = new string[] {"日","金","土"}, ShipName = "阿賀野"},
            new IATable { Equip = "戦闘糧食", Info = "0+戦闘糧食(1)/1/0+戦闘糧食(1)　⇒戦闘糧食(特別なおにぎり)", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "長波"},
            new IATable { Equip = "一式戦 隼II型", Info = "2+九六式艦戦(1)/3+零式艦戦21型(2)/6+12.7mm単装機銃(3)+新型航空兵装資材(1)　⇒一式戦 隼III型甲", Days = new string[] {"月","火","水","木"}, ShipName = "春日丸"},
            new IATable { Equip = "一式戦 隼II型", Info = "2+九六式艦戦(1)/3+零式艦戦21型(2)/6+12.7mm単装機銃(3)+新型航空兵装資材(1)　⇒一式戦 隼III型甲", Days = new string[] {"月","火","水","木"}, ShipName = "あきつ丸"},
            new IATable { Equip = "一式戦 隼II型", Info = "2+九六式艦戦(1)/3+零式艦戦21型(2)/6+12.7mm単装機銃(3)+新型航空兵装資材(1)　⇒一式戦 隼III型甲", Days = new string[] {"水","木","金"}, ShipName = "神威"},
            new IATable { Equip = "一式戦 隼III型甲", Info = "4+零式艦戦52型(3)/6+烈風(2)", Days = new string[] {"月","火"}, ShipName = "あきつ丸"},
            new IATable { Equip = "一式戦 隼III型甲", Info = "4+零式艦戦52型(3)/6+烈風(2)", Days = new string[] {"月","火","水","木"}, ShipName = "春日丸"},
            new IATable { Equip = "一式戦 隼III型甲", Info = "4+零式艦戦52型(3)/6+烈風(2)", Days = new string[] {"木","金"}, ShipName = "神威"},
            new IATable { Equip = "紫電一一型", Info = "4+零式艦戦52型(2)/6+瑞雲(2)/7+紫電改二(2)　⇒紫電二一型 紫電改", Days = new string[] {"月","火","水"}, ShipName = "赤城"},
            new IATable { Equip = "紫電一一型", Info = "4+零式艦戦52型(2)/6+瑞雲(2)/7+紫電改二(2)　⇒紫電二一型 紫電改", Days = new string[] {"月","火","水"}, ShipName = "加賀"},
        };
    }
}

