using Grabacr07.KanColleViewer.Composition;
using Grabacr07.KanColleWrapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ImprovementArsenalPlugin
{
    public class IATable
    {
        public string Equip { get; set; }
        public string[] Days { get; set; }
        public string Kanmusu { get; set; }

        public static IATable[] List = new IATable[] {
            new IATable { Equip = "12.7cm連装砲", Days = new string[] {"日","月","火","水","木","金","土"}, Kanmusu = ""},
            new IATable { Equip = "12.7cm連装砲B型改二", Days = new string[] {"月","火","水"}, Kanmusu = "夕立改二"},
            new IATable { Equip = "12.7cm連装砲B型改二", Days = new string[] {"月","火","水"}, Kanmusu = "綾波改二"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Days = new string[] {"月","火","水","木"}, Kanmusu = "秋月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Days = new string[] {"日","木","金","土"}, Kanmusu = "照月"},
            new IATable { Equip = "14cm単装砲", Days = new string[] {"日","月","火","水","木","金","土"}, Kanmusu = ""},
            new IATable { Equip = "14cm連装砲", Days = new string[] {"月","木"}, Kanmusu = "夕張"},
            new IATable { Equip = "15.2cm連装砲", Days = new string[] {"木","金","土"}, Kanmusu = "阿賀野"},
            new IATable { Equip = "15.2cm連装砲", Days = new string[] {"日","月","金","土"}, Kanmusu = "能代"},
            new IATable { Equip = "15.2cm連装砲", Days = new string[] {"月","火","水","木"}, Kanmusu = "矢矧"},
            new IATable { Equip = "15.2cm連装砲改", Days = new string[] {"水","木","金","土"}, Kanmusu = "矢矧"},
            new IATable { Equip = "15.2cm連装砲改", Days = new string[] {"日","月","火","土"}, Kanmusu = "酒匂"},
            new IATable { Equip = "15.5cm三連装砲", Days = new string[] {"金","土"}, Kanmusu = "最上"},
            new IATable { Equip = "15.5cm三連装砲", Days = new string[] {"日","月"}, Kanmusu = "大淀"},
            new IATable { Equip = "20.3cm連装砲", Days = new string[] {"日","木","金","土"}, Kanmusu = "青葉"},
            new IATable { Equip = "20.3cm連装砲", Days = new string[] {"日","月","火","水","木","金","土"}, Kanmusu = "衣笠"},
            new IATable { Equip = "20.3cm(2号)連装砲", Days = new string[] {"日","月","火"}, Kanmusu = "妙高"},
            new IATable { Equip = "20.3cm(3号)連装砲", Days = new string[] {"火","水"}, Kanmusu = "三隈"},
            new IATable { Equip = "35.6cm連装砲", Days = new string[] {"日","金","土"}, Kanmusu = "扶桑"},
            new IATable { Equip = "38cm連装砲", Days = new string[] {"木","金","土"}, Kanmusu = "Bismarck"},
            new IATable { Equip = "38cm連装砲改", Days = new string[] {"日","月","火"}, Kanmusu = "Bismarck"},
            new IATable { Equip = "381mm/50 三連装砲", Days = new string[] {"火","水","木","金"}, Kanmusu = "Littorio"},
            new IATable { Equip = "381mm/50 三連装砲", Days = new string[] {"日","月","土"}, Kanmusu = "Roma"},
            new IATable { Equip = "381mm/50 三連装砲改", Days = new string[] {"日","月","土"}, Kanmusu = "Littorio"},
            new IATable { Equip = "381mm/50 三連装砲改", Days = new string[] {"火","水","木","金"}, Kanmusu = "Roma"},
            new IATable { Equip = "41cm連装砲", Days = new string[] {"火","金","土"}, Kanmusu = "長門"},
            new IATable { Equip = "41cm連装砲", Days = new string[] {"日","月","木"}, Kanmusu = "陸奥"},
            new IATable { Equip = "試製46cm連装砲", Days = new string[] {"日","月"}, Kanmusu = "大和"},
            new IATable { Equip = "試製46cm連装砲", Days = new string[] {"火","水"}, Kanmusu = "武蔵"},
            new IATable { Equip = "46cm三連装砲", Days = new string[] {"金","土"}, Kanmusu = "大和"},
            new IATable { Equip = "46cm三連装砲", Days = new string[] {"日","月"}, Kanmusu = "武蔵"},
            new IATable { Equip = "試製51cm連装砲", Days = new string[] {"月","火"}, Kanmusu = "大和改"},
            new IATable { Equip = "試製51cm連装砲", Days = new string[] {"月","水"}, Kanmusu = "武蔵改"},
            new IATable { Equip = "90mm単装高角砲", Days = new string[] {"月","火","水","木"}, Kanmusu = "Littorio"},
            new IATable { Equip = "90mm単装高角砲", Days = new string[] {"日","木","金","土"}, Kanmusu = "Roma"},
            new IATable { Equip = "15.2cm単装砲", Days = new string[] {"日","月","火"}, Kanmusu = "阿賀野"},
            new IATable { Equip = "15.2cm単装砲", Days = new string[] {"日","月","土"}, Kanmusu = "金剛"},
            new IATable { Equip = "15.2cm単装砲", Days = new string[] {"月","火","水"}, Kanmusu = "山城"},
            new IATable { Equip = "OTO 152mm三連装速射砲", Days = new string[] {"日","火","水","土"}, Kanmusu = "Littorio"},
            new IATable { Equip = "OTO 152mm三連装速射砲", Days = new string[] {"日","月","木","金"}, Kanmusu = "Roma"},
            new IATable { Equip = "61cm三連装魚雷", Days = new string[] {"木","金","土"}, Kanmusu = "吹雪/吹雪改"},
            new IATable { Equip = "61cm三連装魚雷", Days = new string[] {"日","月","火"}, Kanmusu = "叢雲"},
            new IATable { Equip = "61cm三連装(酸素)魚雷", Days = new string[] {"木","金","土"}, Kanmusu = "吹雪改二"},
            new IATable { Equip = "61cm四連装魚雷", Days = new string[] {"日","月","火","金","土"}, Kanmusu = ""},
            new IATable { Equip = "61cm四連装(酸素)魚雷", Days = new string[] {"日","月","火","水","木","金","土"}, Kanmusu = "大井, 北上"},
            new IATable { Equip = "61cm五連装(酸素)魚雷", Days = new string[] {"水","木"}, Kanmusu = "島風"},
            new IATable { Equip = "13号対空電探", Days = new string[] {"日","木","金","土"}, Kanmusu = "時雨改二"},
            new IATable { Equip = "13号対空電探", Days = new string[] {"日","月","金","土"}, Kanmusu = "五十鈴改二"},
            new IATable { Equip = "13号対空電探", Days = new string[] {"火","水","木"}, Kanmusu = "秋月"},
            new IATable { Equip = "13号対空電探", Days = new string[] {"月","火","水"}, Kanmusu = "照月"},
            new IATable { Equip = "13号対空電探改", Days = new string[] {"木","金","土"}, Kanmusu = "磯風改"},
            new IATable { Equip = "13号対空電探改", Days = new string[] {"日","金","土"}, Kanmusu = "初霜改二"},
            new IATable { Equip = "13号対空電探改", Days = new string[] {"日","月","火","水"}, Kanmusu = "雪風"},
            new IATable { Equip = "22号対水上電探", Days = new string[] {"日","月","金","土"}, Kanmusu = "日向"},
            new IATable { Equip = "22号対水上電探", Days = new string[] {"月","火","金","土"}, Kanmusu = "夕雲"},
            new IATable { Equip = "22号対水上電探", Days = new string[] {"水","木","金","土"}, Kanmusu = "島風"},
            new IATable { Equip = "22号対水上電探改四", Days = new string[] {"日","木","金","土"}, Kanmusu = "妙高改二"},
            new IATable { Equip = "22号対水上電探改四", Days = new string[] {"日","月","金","土"}, Kanmusu = "羽黒改二"},
            new IATable { Equip = "22号対水上電探改四", Days = new string[] {"火","水","木","金"}, Kanmusu = "金剛改二"},
            new IATable { Equip = "21号対空電探", Days = new string[] {"日","月","金","土"}, Kanmusu = "伊勢"},
            new IATable { Equip = "21号対空電探", Days = new string[] {"水","木","金","土"}, Kanmusu = "日向"},
            new IATable { Equip = "21号対空電探改", Days = new string[] {"日","木","金","土"}, Kanmusu = "大和"},
            new IATable { Equip = "21号対空電探改", Days = new string[] {"火","水","木","金"}, Kanmusu = "武蔵"},
            new IATable { Equip = "32号対水上電探", Days = new string[] {"水","木","金","土"}, Kanmusu = "伊勢"},
            new IATable { Equip = "32号対水上電探", Days = new string[] {"日","月","火"}, Kanmusu = "日向"},
            new IATable { Equip = "32号対水上電探改", Days = new string[] {"日","月","火"}, Kanmusu = "伊勢"},
            new IATable { Equip = "32号対水上電探改", Days = new string[] {"水","木","金","土"}, Kanmusu = "日向"},
            new IATable { Equip = "九三式水中聴音機", Days = new string[] {"日","金","土"}, Kanmusu = "夕張"},
            new IATable { Equip = "九三式水中聴音機", Days = new string[] {"月","金","土"}, Kanmusu = "五十鈴改二"},
            new IATable { Equip = "三式水中探信儀", Days = new string[] {"火","水"}, Kanmusu = "夕張"},
            new IATable { Equip = "三式水中探信儀", Days = new string[] {"日","火","水"}, Kanmusu = "五十鈴改二"},
            new IATable { Equip = "九四式爆雷投射機", Days = new string[] {"水","木"}, Kanmusu = ""},
            new IATable { Equip = "三式爆雷投射機", Days = new string[] {"水","木"}, Kanmusu = "五十鈴改二"},
            new IATable { Equip = "九一式徹甲弾", Days = new string[] {"水","木","金","土"}, Kanmusu = "比叡"},
            new IATable { Equip = "九一式徹甲弾", Days = new string[] {"日","月","金","土"}, Kanmusu = "霧島"},
            new IATable { Equip = "一式徹甲弾", Days = new string[] {"日","金","土"}, Kanmusu = "金剛"},
            new IATable { Equip = "一式徹甲弾", Days = new string[] {"月","火","水"}, Kanmusu = "榛名"},
            new IATable { Equip = "25mm連装機銃", Days = new string[] {"日","金","土"}, Kanmusu = "五十鈴改二"},
            new IATable { Equip = "25mm三連装機銃", Days = new string[] {"月","火","水"}, Kanmusu = "五十鈴改二"},
            new IATable { Equip = "25mm三連装機銃", Days = new string[] {"火","水","木"}, Kanmusu = "摩耶/摩耶改"},
            new IATable { Equip = "25mm三連装機銃", Days = new string[] {"日","月","金","土"}, Kanmusu = "摩耶改二"},
            new IATable { Equip = "91式高射装置", Days = new string[] {"日","月","金","土"}, Kanmusu = "摩耶"},
            new IATable { Equip = "91式高射装置", Days = new string[] {"日","月","金","土"}, Kanmusu = "秋月"},
            new IATable { Equip = "91式高射装置", Days = new string[] {"日","木","金","土"}, Kanmusu = "照月"},
            new IATable { Equip = "94式高射装置", Days = new string[] {"日","月","火","水","木","金","土"}, Kanmusu = "秋月"},
            new IATable { Equip = "94式高射装置", Days = new string[] {"日","月","火","水","木","金","土"}, Kanmusu = "照月"},
            new IATable { Equip = "94式高射装置", Days = new string[] {"日","木","金","土"}, Kanmusu = "吹雪改二"},
            new IATable { Equip = "94式高射装置", Days = new string[] {"日","木","金","土"}, Kanmusu = "摩耶改二"},
            new IATable { Equip = "探照灯", Days = new string[] {"木","金","土"}, Kanmusu = "暁"},
            new IATable { Equip = "探照灯", Days = new string[] {"日","金","土"}, Kanmusu = "神通"},
            new IATable { Equip = "探照灯", Days = new string[] {"月","火","水"}, Kanmusu = "青葉"},
            new IATable { Equip = "探照灯", Days = new string[] {"月","火","水"}, Kanmusu = "綾波"},
            new IATable { Equip = "96式150cm探照灯", Days = new string[] {"日","月","金","土"}, Kanmusu = "比叡"},
            new IATable { Equip = "96式150cm探照灯", Days = new string[] {"火","水","木","金"}, Kanmusu = "霧島"},

        };
    }
}
